function [figure1] = createfigure(xdata1, ydata1, zdata1)
%CREATEFIGURE(xdata1, ydata1, zdata1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 15-Dec-2020 13:52:30

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create surf
surf(xdata1,ydata1,zdata1,'Parent',axes1,'FaceColor','interp',...
    'EdgeColor','none');

% Add y tick formatting
datetick('y','mmm', 'keepticks')

% Create zlabel
zlabel('Normalized Amplitude');

% Create ylabel
ylabel('Month of 2018');

% Create xlabel
xlabel('Propogation Time (s)');

% Create title
title('TDGF Emergence in 2018')

view(axes1,[-30.2557894736842 90]);
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties

